version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
      args:
        APP: api
    ports:
      - "3001:3001"
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
      args:
        APP: web
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - .env
