import { Injectable, Logger } from '@nestjs/common';

import { RoadmapGenerationUnavailableException } from '@/common/exceptions/app.exceptions';

import type { AiNode, AiRoadmapOutput, GenerateRoadmapInput } from './types/ai-roadmap.types';

import { AiService } from '../ai/ai.service';

/**
 * Thin wrapper around AiService that builds the roadmap-specific prompt,
 * calls Gemini, and parses + validates the structured JSON response.
 *
 * Responsibilities:
 * - Build a structured prompt (FR-06, FR-09)
 * - Delegate the actual HTTP call to AiService.generateContent()
 * - Parse and type-validate the JSON response
 * - Throw RoadmapGenerationUnavailableException (503) on any failure
 */
@Injectable()
export class AiRoadmapService {
  private readonly logger = new Logger(AiRoadmapService.name);

  constructor(private readonly aiService: AiService) {}

  async generateRoadmap(input: GenerateRoadmapInput): Promise<AiRoadmapOutput> {
    const prompt = this.buildPrompt(input);

    let responseText: string;
    try {
      responseText = await this.aiService.generateContent(prompt);

      this.logger.log('AI roadmap generated successfully', responseText);
    } catch (err) {
      this.logger.error('Gemini generateContent failed', err);
      throw new RoadmapGenerationUnavailableException();
    }

    return this.parseResponse(responseText, input.skillMap);
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  private buildPrompt(input: GenerateRoadmapInput): string {
    const skillCatalog = JSON.stringify(
      input.skillMap.map((s) => ({
        id: s.id,
        name: s.name,
        defaultEstimatedHours: s.defaultEstimatedHours,
      })),
      null,
      2,
    );

    const prerequisiteGraph = JSON.stringify(input.prerequisites, null, 2);

    const quizSummary = input.quizAnswers
      .map((a) => `Q: ${a.question}\nA: ${a.answer}`)
      .join('\n\n');

    const prompt = [
      'You are a personalized IT learning roadmap planner.',
      'Your job is to build a spine-based learning roadmap from leaf skills and structural nodes.',
      'The skill catalog is a CLOSED SET for leaf nodes only: required/optional nodes must come from it, but group/milestone nodes are structural and generated by you.',
      '',
      `Learner goal: "${input.goal}"`,
      `Role: ${input.roleCategory}`,
      `Available time: ${input.hoursPerDay} hours/day until ${input.deadlineDate}`,
      '',
      'Leaf skill catalog JSON array. ONLY required/optional leaf nodes may use these skills:',
      skillCatalog,
      '',
      'Skill prerequisite graph JSON array. This is advisory input for you when deciding which skills to include and how to sequence group nodes in a roadmap:',
      prerequisiteGraph,
      '',
      'Learner profile. Use this to decide which leaf skills to include, how to group/sequence them, and which skills can be optional:',
      quizSummary,
      '',
      'Return JSON only (no markdown fences):',
      '{',
      '  "title": "string",',
      '  "description": "string",',
      '  "nodes": [',
      '    {',
      '      "name": "string",',
      '      "nodeType": "group|milestone|required|optional",',
      '      "description": "string (milestone only; omit or null for group/leaf nodes)",',
      '      "estimatedHours": number (leaf nodes only; use catalog defaultEstimatedHours when available),',
      '      "skillId": "string (required/optional leaf nodes only; omit or null for group/milestone nodes)",',
      '      "children": [ ...nested nodes... ]',
      '    }',
      '  ]',
      '}',
      '',
      'Strict rules:',
      '- Top-level nodes are the roadmap spine and MUST be "group" or "milestone" only.',
      '- Group nodes are structural section containers: skillId MUST be omitted or null; estimatedHours MUST be omitted or null; description MUST be omitted or null.',
      '- Milestone nodes are structural project checkpoints: skillId MUST be omitted or null; estimatedHours MUST be omitted or null; children MUST be omitted or empty; description MUST contain a concrete project brief.',
      '- Required/optional nodes are leaf skill nodes: they MUST be children of group nodes, MUST use skillId from the leaf skill catalog, and name MUST exactly equal the selected catalog skill name.',
      '- Required/optional leaf nodes MUST NOT have children.',
      '- Do NOT use catalog skills as group or milestone nodes. Catalog skills are only for required/optional leaves.',
      '- Use each selected leaf skill at most once in the whole roadmap.',
      '- Use the prerequisite graph as advisory sequencing context: if skill A depends on prerequisite B and both are selected, place B in an earlier group or earlier within the same group than A.',
      '- The prerequisite graph must not be represented as UI arrows and must not imply runtime unlock logic. Runtime unlock is spine-sequential by group/milestone order.',
      '- Generate group nodes with coherent names such as "Internet Basics", "Backend Language", "Databases", "API Security", or similar structural section labels. The number and sequencing of groups should be determined by the provided skill set and the learner profile.',
      '- Generate at least 2-3 milestone nodes interspersed among groups, not all at the end.',
      '- This roadmap MUST be exhaustive and production-grade. You MUST use as many skills from the catalog as possible.',
      // `- The provided catalog contains exactly ${input.skillMap.length} skills. You MUST include at least ${Math.floor(input.skillMap.length * 0.8)} of these skills in the roadmap as required or optional nodes.`,
      '- Each group node MUST contain a limited number of leaf skills to ensure clarity and progressive learning.',
      '- A group node MUST contain between 3 to 6 leaf nodes maximum. NEVER exceed 3 skills in a single group.',
      '- Each domain MUST be split into clear stages: fundamentals → intermediate → advanced. Avoid mixing beginner and advanced topics in the same group.',
      '- If a topic contains too many related skills, you MUST split it into multiple smaller, logically progressive group nodes.',
      '- Prefer more groups with focused scope rather than fewer groups with too many skills.',
      '- Each group should represent a clear, narrow learning theme (e.g., "SQL Fundamentals", "Database Optimization", instead of one large "Databases" group).',
      '- Groups should be balanced in size. Avoid highly uneven groups (e.g., one group with 20 skills and another with 3).',
      '- The roadmap must feel like step-by-step progression, not a bulk collection of skills.',
      '- When organizing skills, prioritize learning flow over grouping by category alone.',
      '- Break down complex domains (e.g., Databases, Security, Architecture) into multiple stages from basic → advanced.',
      '- Avoid dumping all advanced topics into a single group. Spread them across later groups progressively.',
      "- ONLY omit a skill from the catalog if it is completely irrelevant to the learner's goal, or if the learner explicitly stated they have already mastered it.",
      '- Mark nice-to-have or less critical skills as "optional" rather than omitting them entirely.',
    ].join('\n');

    this.logger.log('AI roadmap prompt', prompt);
    return prompt;
  }

  private parseResponse(
    text: string,
    skillCatalog: GenerateRoadmapInput['skillMap'],
  ): AiRoadmapOutput {
    const cleaned = this.stripMarkdownFences(text);

    let parsed: unknown;
    try {
      parsed = JSON.parse(cleaned);
    } catch (err) {
      this.logger.error('Failed to parse Gemini JSON response', { raw: text, err });
      throw new RoadmapGenerationUnavailableException();
    }

    if (!this.isValidAiRoadmapOutput(parsed)) {
      this.logger.error('Gemini response failed schema validation', { parsed });
      throw new RoadmapGenerationUnavailableException();
    }

    return this.normalizeRoadmapOutput(parsed, skillCatalog);
  }

  private normalizeRoadmapOutput(
    output: AiRoadmapOutput,
    skillCatalog: GenerateRoadmapInput['skillMap'],
  ): AiRoadmapOutput {
    const skillById = new Map(skillCatalog.map((s) => [s.id, s]));
    const usedSkillIds = new Set<string>();

    const normalizeNode = (node: AiNode): AiNode => {
      if (node.nodeType === 'group') {
        return {
          name: node.name,
          nodeType: node.nodeType,
          children: node.children?.map(normalizeNode),
        };
      }

      if (node.nodeType === 'milestone') {
        return {
          name: node.name,
          nodeType: node.nodeType,
          description: node.description,
        };
      }

      const skillId = node.skillId;
      if (!skillId) {
        this.logger.error('Gemini response returned a leaf node without skillId', { node });
        throw new RoadmapGenerationUnavailableException();
      }

      const skill = skillById.get(skillId);
      if (!skill || usedSkillIds.has(skillId)) {
        this.logger.error('Gemini response used an invalid or duplicated leaf skillId', {
          node,
          skillId,
        });
        throw new RoadmapGenerationUnavailableException();
      }

      usedSkillIds.add(skillId);

      return {
        nodeType: node.nodeType,
        skillId,
        name: skill.name,
        estimatedHours: node.estimatedHours ?? skill.defaultEstimatedHours ?? undefined,
      };
    };

    return {
      ...output,
      nodes: output.nodes.map(normalizeNode),
    };
  }

  private stripMarkdownFences(text: string): string {
    const trimmed = text.trim();
    if (trimmed.startsWith('```')) {
      return trimmed
        .replace(/^```(?:json)?/i, '')
        .replace(/```$/, '')
        .trim();
    }
    return trimmed;
  }

  private isValidAiRoadmapOutput(value: unknown): value is AiRoadmapOutput {
    if (!value || typeof value !== 'object') return false;
    const v = value as Record<string, unknown>;
    if (typeof v['title'] !== 'string' || !v['title']) return false;
    if (typeof v['description'] !== 'string') return false;
    if (!Array.isArray(v['nodes']) || v['nodes'].length === 0) return false;
    return v['nodes'].every((n) => this.isValidAiNode(n, null));
  }

  private isValidAiNode(value: unknown, parentType: AiNode['nodeType'] | null): value is AiNode {
    if (!value || typeof value !== 'object') return false;
    const n = value as Record<string, unknown>;
    if (typeof n['name'] !== 'string' || !n['name']) return false;
    const validTypes = ['group', 'milestone', 'required', 'optional'];
    if (typeof n['nodeType'] !== 'string' || !validTypes.includes(n['nodeType'])) return false;
    const nodeType = n['nodeType'] as AiNode['nodeType'];

    if (parentType === null && nodeType !== 'group' && nodeType !== 'milestone') return false;
    if (parentType === 'group' && nodeType !== 'required' && nodeType !== 'optional') return false;
    if (parentType !== null && parentType !== 'group') return false;

    const skillId = n['skillId'];
    if (nodeType === 'required' || nodeType === 'optional') {
      if (typeof skillId !== 'string' || !skillId) return false;
    } else if (skillId !== undefined && skillId !== null) {
      return false;
    }

    const description = n['description'];
    const estimatedHours = n['estimatedHours'];
    if (nodeType === 'milestone') {
      if (typeof description !== 'string' || !description) return false;
      if (estimatedHours !== undefined && estimatedHours !== null) return false;
    } else if (nodeType === 'group') {
      if (description !== undefined && description !== null) return false;
      if (estimatedHours !== undefined && estimatedHours !== null) return false;
    } else {
      if (description !== undefined && description !== null) return false;
      if (
        estimatedHours !== undefined &&
        estimatedHours !== null &&
        typeof estimatedHours !== 'number'
      ) {
        return false;
      }
    }

    if (n['children'] !== undefined && !Array.isArray(n['children'])) return false;
    if (nodeType === 'group') {
      if (!Array.isArray(n['children']) || n['children'].length === 0) return false;
      if (!(n['children'] as unknown[]).every((c) => this.isValidAiNode(c, nodeType))) return false;
    } else if (Array.isArray(n['children']) && n['children'].length > 0) {
      return false;
    }

    return true;
  }
}
