import type { INestApplication } from '@nestjs/common';
import type { App } from 'supertest/types';

import { Test } from '@nestjs/testing';

import type { GenerateRoadmapInput } from '@/modules/roadmaps/types/ai-roadmap.types';

import { AppModule } from '@/app.module';
import { configureApp } from '@/app.setup';
import { AiService } from '@/modules/ai/ai.service';
import { PrismaService } from '@/modules/prisma/prisma.service';

import { getDatabaseSafetySkipReason } from './database';

type IntegrationApp = {
  app: INestApplication<App>;
  prisma: PrismaService;
};

export async function createIntegrationApp(): Promise<IntegrationApp> {
  process.env.JWT_SECRET ??= 'test-access-secret';
  process.env.JWT_REFRESH_SECRET ??= 'test-refresh-secret';
  process.env.JWT_REFRESH_TOKEN_HASH_SECRET ??= 'test-refresh-hash-secret';
  process.env.CLIENT_URL ??= 'http://localhost:3000';

  const databaseSafetySkipReason = getDatabaseSafetySkipReason();
  if (databaseSafetySkipReason) {
    throwIntegrationPreflightFailure(databaseSafetySkipReason);
  }

  const aiServiceMock = {
    generateContent: () => Promise.resolve(''),
    generateNodeQuiz: () =>
      Promise.resolve(
        Array.from({ length: 8 }, (_value, index) => ({
          correctOption: 'A' as const,
          optionA: `Correct answer ${index + 1}`,
          optionB: `Wrong answer B${index + 1}`,
          optionC: `Wrong answer C${index + 1}`,
          optionD: `Wrong answer D${index + 1}`,
          questionText: `Generated quiz question ${index + 1}?`,
        })),
      ),
    generateOnboardingQuiz: () =>
      Promise.resolve(
        JSON.stringify({
          roleCategory: 'web-development',
          questions: [{ question: 'What do you want to build?', possibleAnswers: ['Web apps'] }],
        }),
      ),
    generateRoadmap: (input: GenerateRoadmapInput) => {
      const firstSkill = input.skillMap[0];
      const secondSkill = input.skillMap[1] ?? firstSkill;

      return Promise.resolve(
        JSON.stringify({
          description: 'Generated by the integration AI mock',
          nodes: [
            {
              children: [
                {
                  estimatedHours: firstSkill?.defaultEstimatedHours ?? 4,
                  name: firstSkill?.name ?? 'Generated Skill',
                  nodeType: 'required',
                  skillId: firstSkill?.id,
                },
                {
                  estimatedHours: secondSkill?.defaultEstimatedHours ?? 3,
                  name: secondSkill?.name ?? 'Generated Optional Skill',
                  nodeType: 'optional',
                  skillId: secondSkill?.id,
                },
              ],
              name: 'Generated Foundations',
              nodeType: 'group',
            },
            {
              description: 'Ship a small working project',
              name: 'Generated Capstone',
              nodeType: 'milestone',
            },
          ],
          title: 'Generated Integration Roadmap',
        }),
      );
    },
  };

  const moduleFixture = await Test.createTestingModule({
    imports: [AppModule],
  })
    .overrideProvider(AiService)
    .useValue(aiServiceMock)
    .compile();

  const app: INestApplication<App> = moduleFixture.createNestApplication();
  configureApp(app);
  await app.init();
  const prisma = moduleFixture.get(PrismaService);

  try {
    await prisma.$queryRawUnsafe('SELECT 1');
  } catch {
    await app.close();

    throwIntegrationPreflightFailure(
      'DATABASE_URL is not reachable. Start the disposable test database first.',
    );
  }

  return {
    app,
    prisma,
  };
}

function throwIntegrationPreflightFailure(reason: string): never {
  throw new Error(
    `API integration test database is not ready: ${reason} ` +
      'Set up the disposable test database before running integration tests.',
  );
}
