/*
  Warnings:

  - The values [FRONTEND,BACKEND,MOBILE,DATA,FULL_STACK,DEVSECOPS,DATA_ANALYST,AI_ENGINEER,AI_AND_DATA_SCIENTIST,DATA_ENGINEER,ANDROID,MACHINE_LEARNING,POSTGRESQL,IOS,QA,SOFTWARE_ARCHITECT,UX_DESIGN,TECHNICAL_WRITER,GAME_DEVELOPER,SERVER_SIDE_GAME_DEVELOPER,MLOPS,PRODUCT_MANAGER,ENGINEERING_MANAGER,DEVELOPER_RELATIONS,BI_ANALYST] on the enum `RoleCategory` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "RoleCategory_new" AS ENUM ('WEB_DEVELOPMENT', 'FRAMEWORKS', 'ABSOLUTE_BEGINNERS', 'LANGUAGES_AND_PLATFORMS', 'DEVOPS', 'DATABASES', 'COMPUTER_SCIENCE', 'DESIGN', 'BEST_PRACTICES', 'AI_AND_MACHINE_LEARNING', 'DATA_ANALYSIS', 'MOBILE_DEVELOPMENT', 'MANAGEMENT', 'GAME_DEVELOPMENT', 'BLOCKCHAIN', 'CYBER_SECURITY');
ALTER TABLE "roadmaps" ALTER COLUMN "role_category" TYPE "RoleCategory_new" USING ("role_category"::text::"RoleCategory_new");
ALTER TABLE "skills" ALTER COLUMN "role_category" TYPE "RoleCategory_new" USING ("role_category"::text::"RoleCategory_new");
ALTER TYPE "RoleCategory" RENAME TO "RoleCategory_old";
ALTER TYPE "RoleCategory_new" RENAME TO "RoleCategory";
DROP TYPE "public"."RoleCategory_old";
COMMIT;
